
public class ExceptionsDemo {

	public static void main(String[] args) {

		try{
			System.out.println(10/2);
		System.out.println("try");	
		}
		
		catch (ArithmeticException e) {
			e.printStackTrace();
			System.out.println("catch");
		}
		finally {
			System.out.println("finaly block");
		//resource deallocate which gets executed irrespective of try or catch
		}
		
		System.out.println("test line");
		
	}

}
